// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unistream.Transaction.Persistence.Database;

#nullable disable

namespace Unistream.Transaction.Persistence.Database.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Unistream.Transaction.Persistence.Entities.ClientBalanceEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<decimal>("Balanace")
                        .HasColumnType("TEXT")
                        .HasColumnName("balanace");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date_time");

                    b.HasKey("ClientId")
                        .HasName("pk_client_balance");

                    b.ToTable("client_balance", (string)null);
                });

            modelBuilder.Entity("Unistream.Transaction.Persistence.Entities.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_balance");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_time");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_reverted");

                    b.Property<DateTime?>("RevertedDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("reverted_date_time");

                    b.Property<DateTime>("SysCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("sys_created");

                    b.Property<decimal>("UpdatedBalance")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_balance");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_transaction_client_id");

                    b.HasIndex("DateTime")
                        .HasDatabaseName("ix_transaction_date_time");

                    b.HasIndex("SysCreated")
                        .HasDatabaseName("ix_transaction_sys_created");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("Unistream.Transaction.Persistence.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Unistream.Transaction.Persistence.Entities.ClientBalanceEntity", "ClientBalance")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_client_balance_client_id");

                    b.Navigation("ClientBalance");
                });

            modelBuilder.Entity("Unistream.Transaction.Persistence.Entities.ClientBalanceEntity", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
